name: f-spot
version: 0.8-2018-11-24
summary: F-Spot Photo Manager
description: |
  F-Spot is a full-featured personal photo management application for the
  GNOME desktop. It simplifies digital photography by providing intuitive
  tools to help you share, touch-up, find and organize your images.
  It allows for importing of your existing photo collections, tagging photos
  with identifiers, as well as doing simple edits of photos (e.g. rotating).

grade: devel
confinement: strict

parts:
  mono:
    plugin: nil
    override-pull: |
      apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
      echo "deb https://download.mono-project.com/repo/ubuntu stable-xenial main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
      apt update
      apt install -y mono-devel nuget
    build-packages:
      - apt-transport-https
  f-spot:
    build-packages:
      - libgtk2.0-dev
      - intltool
      - libgconf2-dev 
      - libgtk2.0-cil-dev
      - libdbus-glib2.0-cil-dev
      - libgconf2.0-cil-dev
      - gnome-icon-theme
      - gtk-sharp2-gapi
      - libgnome2.0-cil-dev
      - libjpeg-dev
      - liblcms2-dev
      - libunique-dev
      - libgnome-vfs2.0-cil-dev
      - libgnome-keyring1.0-cil-dev
      - libgnomeui-dev
      - gnome-doc-utils
    plugin: autotools
    configflags: ["--enable-tests"]
    after:
      - mono
