#!/bin/sh -e

#$SNAP/usr/share/cli-common/policy-install glib-sharp 2.4
#$SNAP/usr/share/cli-common/policy-install glib-sharp 2.10
#$SNAP/usr/share/cli-common/policy-install glib-sharp 2.8
#$SNAP/usr/share/cli-common/policy-install glib-sharp 2.6
#chroot $SNAP $SNAP/usr/share/cli-common/gac-package-install libglib2.0-cil >> $SNAP_DATA/install.log

PKG_DIR=$SNAP/usr
export MONO_PATH=$PKG_DIR/lib/mono/4.5
export MONO_CONFIG=$SNAP/etc/mono/config
export MONO_CFG_DIR=$PKG_DIR/etc
#export C_INCLUDE_PATH=${PKG_DIR}/include
export MONO_REGISTRY_PATH=~/.mono/registry
export MONO_GAC_PREFIX=$PKG_DIR/lib/mono/gac/

cd $SNAP/usr/lib/cli/glib-sharp-2.0
$PKG_DIR/bin/mono --config $MONO_CONFIG $MONO_PATH/gacutil.exe -i glib-sharp.dll
 
